### ISSUE TITLE
Support library version 25.0.0

### ISSUE THREAD

**Issue by hypeapps** [passsy/CompositeAndroid#34]
I would like use support library version 25.0.0 with CompositeAndroid but I got error:

> Error:Could not find com.pascalwelsch.compositeandroid:activity:25.0.0.

Can you update CompositeAndroid to 25.0.0 ?

**Comment by passsy** [comment]
https://github.com/passsy/CompositeAndroid/releases/tag/v25.0.0 binaries are uploaded.

#30
