### ISSUE TITLE
getFragment() is null

### ISSUE THREAD

**Issue by Martin-Hogge** [passsy/CompositeAndroid#49]
Not sure I really understood how this is working. I want to use some methods that needs a context inside my `FragmentPlugin` (such as getString(), etc.). I tought I would simply use `getFragment().getString()` or `getCompositeDelegate().getString()` but both `getFragment()` and `getCompositeDelegate()` returns null.

How should I refer to the hosting fragment? Should I add it through my default constructor?

Thank's !

**Comment by passsy** [comment]
It seems like you didn't add the plugin to your `Fragment` with `addPlugin(myFragmentPlugin);`. [This](https://github.com/passsy/CompositeAndroid/blob/master/core/src/main/java/com/pascalwelsch/compositeandroid/core/AbstractDelegate.java#L22) is where the connection will be made and `getFragment()` will return the `Fragment` the plugin is added to.

**Comment by Martin-Hogge** [comment]
Wow sorry it seems I missed that. Thank's for the help !
