### ISSUE TITLE
Mosby usage: missing `onRetainCustomNonConfigurationInstance` method in ActivityPlugin

### ISSUE THREAD

**Issue by mkoslacz** [passsy/CompositeAndroid#50]
Hi,

Encouraged by your usecase reccomendation: 

> - gradually add libraries like Mosby (without extending from a MvpActivity) or Flow to your Activities when you need it

I have started extending`ActivityPlugin` in way that will allow me to have [Mosby](https://github.com/sockeqwe/mosby) presenter attached to it. 

I have noticed that in `ActivityPlugin` there is `onRetainNonConfigurationInstance` method, although the documentation states clearly:

>     Retain all appropriate fragment and loader state. You can NOT
>     override this yourself! Use {@link #onRetainCustomNonConfigurationInstance()}
>     if you want to retain your own state.

and moreover the `onRetainCustomNonConfigurationInstance` method is missing there. 

I wanted to override the `onRetainCustomNonConfigurationInstance` method in way it is done in Mosby `MvpActivity` to support Presenter lifecycle, but as I said, there is no such method in `ActivityPlugin`. Have you tried using Mosby with CompositeAndroid? Shall I do it in some other way?

**Comment by passsy** [comment]
`onRetainCustomNonConfigurationInstance` was one of the most challenging pieces of this lib which required some manual code. Here is how it works:

```kotlin
class MyPlugin : ActivityPlugin() {

    var presenter: String? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        presenter = getLastNonConfigurationInstance("myPlugin") as String?
        if (presenter == null) {
            presenter = "MyPresenter"
        }
    }

    override fun onRetainNonConfigurationInstance(): CompositeNonConfigurationInstance {
        return CompositeNonConfigurationInstance("myPlugin", presenter)
    }
}
```

You must define a unique key for your plugin to get *your* non configuraiton instance again. I should fix the documentation

You could use [ThirtyInch](https://github.com/grandcentrix/ThirtyInch) which already has a [plugin](https://github.com/grandcentrix/ThirtyInch#compositeandroid)
