### ISSUE TITLE
Can you please release a 27.0.2 version?

### ISSUE THREAD

**Issue by changxiangzhong** [passsy/CompositeAndroid#60]
Android support 27.0.2 has been there for quite a while. It would be great if we can use the latest version.

**Comment by Yukooo** [comment]
Up to 27.1.1

**Comment by Yukooo** [comment]
Up to 28.0.0 and Android X

**Comment by passsy** [comment]
<img width="300" alt="screen-shot-2018-10-26-13-58-51 53" src="https://user-images.githubusercontent.com/1096485/47565026-4e92de00-d927-11e8-8047-a8fc60532ff5.png">
All released except for AndroidX
