### ISSUE TITLE
Use Dagger2 injected objects in Plugin

### ISSUE THREAD

**Issue by markusressel** [passsy/CompositeAndroid#61]
Hi,

I really like this library and it has brought some great improvements into my code. Thanks :-)
However I'm facing a challenge now:

I'm using Dagger2 as a dependency injection framework in my app.
I have a (CompositeAndroid) plugin that needs to have access to some injected classes.
However since plugins are added in the constructor of an Activity (or Fragment) and fields are injected in ```onCreate()``` of the root base Activity it is not possible to access injected fields on construction so I cannot pass it as a parameter to the plugin from the Activity.

Example:
```
abstract class LockableSupportActivityBase : DaggerSupportActivityBase() {

    @Inject
    protected lateinit var preferenceHandler: PreferenceHandler

    init {
        // this throws NotInitializedException on "preferenceHandler"
        addActivityPlugins(LockPlugin(preferenceHandler))
    }

}
```

Injecting the Plugin itself is also not possible since it has to be added to the Activity in the constructor and the activity also has access to injected properties only right after ```super.onCreate()``` (so it's too late).

Example:
```
abstract class LockableSupportActivityBase : DaggerSupportActivityBase() {

    @Inject
    protected lateinit var lockPlugin: LockPlugin

    init {
        // this throws NotInitializedException on "lockPlugin"
        addActivityPlugins(lockPlugin)
    }

}
```

Is there a way to work around this or is this a problem that needs a more sophisticated fix?

**Comment by passsy** [comment]
instead of passing the object directly into your plugin you could pass a method returning the object.
```kotlin
class LockPlugin(val preferenceHandlerProvider: ()-> PreferenceHandler) : ActivityPlugin { ... }
```

```kotlin
    init {
        addActivityPlugins(LockPlugin( { preferenceHandler } ))
    }
```

**Comment by markusressel** [comment]
Ah that's a great idea!
Thanks for the quick reponse.
I will try it tomorrow though since it's 4 a clock in the morning around here... :D

**Comment by markusressel** [comment]
It works!

Although it's kind of a workaround it's not that bad so I can live with it.

Thx for the quick help :)
