### ISSUE TITLE
Update to Oreo ApiLevel 26 ambiguous findViewById(int)

### ISSUE THREAD

**Issue by wman1980** [passsy/CompositeAndroid#69]
After I updated my compileSdk and targetSdk to 26 I got the following error in several classes:

> error: reference to findViewById is ambiguous
both method findViewById(int) in AppCompatActivity and method <T>findViewById(int) in CompositeActivity match
where T is a type-variable:
T extends View declared in method <T>findViewById(int)

Any idea how to fix it?

Thanks & Regards

**Comment by wman1980** [comment]
as a workaround I am now using `super_findViewById`, but thats not very nice.

**Comment by passsy** [comment]
Could it be that you have a version missmatch between CompositeAndroid and the support library? You have to upgrade CompositeAndroid to `26+` as well.
 It works fine in the [sample](https://github.com/passsy/CompositeAndroid/blob/9a95de091c360dde2b96ba18bb284f0029889829/sample/src/main/java/com/pascalwelsch/compositeandroid/MainActivity.java#L21).

**Comment by wman1980** [comment]
support lib:
` implementation "com.android.support:appcompat-v7:27.1.1"`

composite android:
`implementation "com.pascalwelsch.compositeandroid:activity:27.1.1"
 implementation "com.pascalwelsch.compositeandroid:fragment:27.1.1"`

![image](https://user-images.githubusercontent.com/3774028/43718502-22212d08-998b-11e8-8c4b-9cf74aa5f5cc.png)

Within CompositeActivity:
![image](https://user-images.githubusercontent.com/3774028/43720204-237217b2-9990-11e8-97f5-7bfeecaf6955.png)

![image](https://user-images.githubusercontent.com/3774028/43720270-57104c88-9990-11e8-89f5-d3f127d1163d.png)

**Comment by wman1980** [comment]
ahh, fixed it. There was a compatibility issue.

```
// keep all support libs the same
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion "25.2.0"
            }
        }

    }
}
```

thanks & sorry
